SELECT 
	CASE WHEN ddgf.FACET_SUBCATEGORY = 0 THEN 'INDIVIDUAL CONTRIBUTOR' ELSE 'PEOPLE MANAGER' END as emp_type
	, ddgf.REQ_VALUE as opened_reqs
	, ddgf.SNAPSHOT_DATE 
FROM 
	BOOKER.D_DAILY_GLOBAL_FACETS ddgf
WHERE 
	ddgf.SNAPSHOT_DATE between DATE(NOW() - INTERVAL 20 DAY) AND DATE(NOW()) AND 
	ddgf.MAIN_FACET_CATEGORY  = 'is_manager'

UNION ALL 

SELECT 
	'TOTAL' as emp_type
	, sum(ddgf.REQ_VALUE) as opened_reqs
	, ddgf.SNAPSHOT_DATE 
FROM 
	BOOKER.D_DAILY_GLOBAL_FACETS ddgf
WHERE 
	ddgf.SNAPSHOT_DATE between DATE(NOW() - INTERVAL 20 DAY) AND DATE(NOW()) AND 
	ddgf.MAIN_FACET_CATEGORY  = 'is_manager'
GROUP BY 
	ddgf.SNAPSHOT_DATE